version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_SPACY_MODEL: "true"
    container_name: rubitherm-app
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "-m", "src.main"]